---
title: "qbs181-final"
author: "Xiangyun Rui"
date: "11/26/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RODBC)
library(tidyr)
library(dplyr)
library(lubridate)
#connecting RODBC
myconn <- odbcConnect("qbs181","xrui","xrui@qbs181")
#importing Demographics,Conditions,TextMessages
q_demo <- sqlQuery(myconn,"select * from Demographics")
head(q_demo,10)
q_cond <- sqlQuery(myconn,"select * from Conditions")
head(q_cond,10)
q_mess <- sqlQuery(myconn,"select * from TextMessages")
head(q_mess,10)

#merge q_demo and q_cond
q4 <- merge(q_demo,q_cond, by.x="contactid",by.y="tri_patientid")
head(q4,10)
#merge q4 and q_mess
q5 <- merge(q4,q_mess, by.x="contactid",by.y="tri_contactId")
head(q5,10)

#final dataset
q5$TextSentDate <- mdy(q5$TextSentDate)
q5$TextSentDate<-as.Date(q5$TextSentDate)
q6 <- q5 %>%
  group_by(contactid) %>% 
  slice(which.max(TextSentDate))
head(q6,10)
```




